With Trips as (
select
RIDE_ID,
DATE(TO_TIMESTAMP(STARTED_AT)) as TRIP_DATE,
START_STATIO_ID as START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) as TRIP_DURATION_SECONDS

From {{ ref('stage_bike') }}
where RIDE_ID != 'ride_id'


)
Select * from Trips